# Generated by Django 4.0.4 on 2022-05-26 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tariff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название тарифа')),
                ('minutes', models.IntegerField(verbose_name='Количество минут в секундах')),
                ('gigabytes', models.IntegerField(verbose_name='Количество гигабайт в мегабайтах')),
                ('sms', models.IntegerField(verbose_name='Количество СМС')),
                ('price', models.IntegerField(verbose_name='Цена')),
            ],
        ),
    ]
