# Generated by Django 4.0.4 on 2022-05-26 22:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tariff',
            name='customer',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='UsedResources',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minutes', models.IntegerField(verbose_name='Количество использованных минут в секундах')),
                ('gigabytes', models.IntegerField(verbose_name='Количество использованных гигабайт в мегабайтах')),
                ('sms', models.IntegerField(verbose_name='Количество использованных СМС')),
                ('customer', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
