# Generated by Django 4.0.4 on 2022-05-26 22:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('api', '0002_tariff_customer_usedresources'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tariff',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='usedresources',
            name='customer',
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('base_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('tariff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.tariff')),
                ('used_resources', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.usedresources')),
            ],
        ),
    ]
