# Generated by Django 4.0.4 on 2022-05-29 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_review'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='user_name',
            new_name='username',
        ),
    ]
